### ISSUE TITLE
Gaia Sky crashes on Windows 10, Java 1.8.0_101

### ISSUE THREAD

**Issue by tlskillman** [ari-zah/gaiasky#79] opened 2016-09-25 14:59 UTC
On first install, Gaia Sky started up, and then crashed. Restarted and got to earth-and-sky image with control panel, but after about 30 secs crashed. Read docs here (https://zah.uni-heidelberg.de/?id=660) where it suggested deleting $HOME/.gaiasky/global.properties and C:\Users\$username\.gaiasky. Did so, restarted, crashed before any display.  Rebooted, Gaia crashed on startup, no display. Reinstalled, Gaia crashed on startup, no display.

Any help appreciated.  I'm running on a high end PC with NVIDIA GTX 980 Ti with Vive VR hardware. Looking forward to trying your system out.

**Comment by tlskillman** [comment] 2016-09-25 15:04
Just noticed Issue 7. Tried running as Admin, no difference.  Here are my log and error files.  (Note: I had to rename them to .txt files so github would upload them.)

[error.txt](https://github.com/ari-zah/gaiasky/files/491719/error.txt)
[output.txt](https://github.com/ari-zah/gaiasky/files/491720/output.txt)

**Comment by tlskillman** [comment] 2016-09-25 15:46
![image](https://cloud.githubusercontent.com/assets/4645276/18816339/973eeef6-82fc-11e6-837a-22f7f552c507.png)

**Comment by tlskillman** [comment] 2016-09-25 17:23
Update: Found part of issue. When GaiaSky crashes there is a background processes that has to be killed manually (via task manager) before restarting.  For clean install I rebooted, uninstalled GaiaSky, found a .gaiasky file in my home directory that I also deleted, then reinstalled 64 bit version. Restarted GaiaSky and it ran better. Crashed after about 5 minutes.  Still testing...

**Comment by tlskillman** [comment] 2016-09-25 17:54
Seems to be more stable now. Not sure why. Changed some preferences related to graphics and rendering, unfortunately not sure which change improved stability. I will let you know if I figure it out.

Now just trying to get it to render in the Vive hardware. Not too obvious how to do that...yet...

**Comment by langurmonkey** [comment] 2016-09-26 06:59
I can't be sure what the real issue is because I do not use Windows 10 (I have a machine with a Windows 7 partition laying around that I use only for testing), but I've had reports mentioning that tweaking graphics performance settings in Windows 10 may settle some issues. For instance, [this issue](https://github.com/ari-zah/gaiasky/issues/76).
The error log in your second message seems to be caused by a bug which was already fixed ([see here](https://github.com/ari-zah/gaiasky/issues/75)). The fix will make it into the `1.0.1 version`, to be released soon.

**Comment by langurmonkey** [comment] 2016-10-05 13:56
I will close this bug if no longer active. Windows 10 seems to give problems and needs some tweaking of graphics performance values in the OS.

**Comment by tlskillman** [comment] 2016-10-05 15:07
Ok. Nice tool. Thx.

**Closed** 2016-10-06 06:52 UTC
